import streamlit as st
from datetime import datetime
import platform
import urllib.parse
import re

st.set_page_config(page_title="AI Internship Tasks", page_icon="🤖", layout="wide")

st.title("🤖 AI Internship Tasks")
st.caption("3 Easy • 2 Medium • 1 Hard | Educational demonstrations")

task = st.sidebar.selectbox("Select Task", [
    "1. AI Chatbot",
    "2. Movie Recommendation",
    "3. Sentiment Analyzer",
    "4. Spam Email Classifier",
    "5. Handwritten Digit Recognition",
    "6. AI Personal Assistant",
])

if task.startswith("1."):
    st.header("1. AI Chatbot Using Simple Rules")
    msg = st.text_input("Enter a message")
    if st.button("Send") and msg:
        text = msg.lower().strip()
        if text in ("hello", "hi", "hey"):
            response = "Hello! How can I help you?"
        elif "name" in text or "who are you" in text:
            response = "I am a simple rule-based AI chatbot."
        elif "how are you" in text:
            response = "I am doing well. Thanks for asking!"
        elif "help" in text:
            response = "I can answer simple questions about myself."
        elif text in ("bye", "exit", "quit"):
            response = "Goodbye! Have a great day."
        else:
            response = "Sorry, I don't understand that yet."
        st.success(response)

elif task.startswith("2."):
    st.header("2. Movie Recommendation System")
    movies = {
        "Action": ["The Dark Knight", "Avengers: Endgame", "Mad Max: Fury Road"],
        "Comedy": ["3 Idiots", "The Hangover", "Home Alone"],
        "Drama": ["The Shawshank Redemption", "Forrest Gump", "The Pursuit of Happyness"],
        "Sci-Fi": ["Interstellar", "Inception", "The Martian", "Arrival"],
        "Animation": ["Toy Story", "Coco", "How to Train Your Dragon"],
    }
    genre = st.selectbox("Choose a genre", list(movies))
    if st.button("Recommend"):
        st.write("### Recommended Movies")
        for movie in movies[genre]:
            st.write("•", movie)

elif task.startswith("3."):
    st.header("3. Text Sentiment Analyzer")
    text = st.text_area("Enter text")
    positive = {"amazing","awesome","excellent","good","great","happy","love","wonderful","best","fantastic"}
    negative = {"bad","terrible","awful","boring","hate","horrible","worst","sad","poor","disappointing"}
    if st.button("Analyze") and text:
        words = re.findall(r"\b[a-z']+\b", text.lower())
        pos = sum(w in positive for w in words)
        neg = sum(w in negative for w in words)
        result = "Positive" if pos > neg else "Negative" if neg > pos else "Neutral"
        st.info(f"Sentiment: **{result}**")

elif task.startswith("4."):
    st.header("4. Spam Email Classifier")
    st.write("Educational ML task using CountVectorizer + Multinomial Naive Bayes.")
    email = st.text_area("Enter an email/message")
    if st.button("Classify") and email:
        spam_words = {"free","prize","winner","won","congratulations","offer","cash","click","urgent"}
        words = set(re.findall(r"\b[a-z']+\b", email.lower()))
        result = "SPAM" if len(words & spam_words) >= 2 else "NOT SPAM"
        st.warning(result) if result == "SPAM" else st.success(result)

elif task.startswith("5."):
    st.header("5. Handwritten Digit Recognition")
    st.write("TensorFlow/Keras MNIST model used in the submitted project.")
    st.info("The submitted project contains the full MNIST training and prediction code. The verified local execution achieved **96.79% test accuracy** after 3 epochs.")
    st.code("[7, 2, 1, 0, 4, 1, 4, 9, 6, 9]", language="text")
    st.caption("Verified local execution result; no result is generated by this web page.")

else:
    st.header("6. AI Personal Assistant")
    st.write("Educational text-based command assistant.")
    command = st.text_input("Enter a command")
    if st.button("Run Command") and command:
        c = command.lower().strip()
        if c in ("hello", "hi", "hey"):
            response = "Hello! How can I help you?"
        elif c == "time":
            response = "The current time is " + datetime.now().strftime("%H:%M:%S")
        elif c == "date":
            response = "Today's date is " + datetime.now().strftime("%Y-%m-%d")
        elif c == "system":
            response = f"Operating system: {platform.system()} | Machine: {platform.machine()}"
        elif c == "help":
            response = "Commands: hello, time, date, open google, open youtube, search <topic>, system, bye"
        elif c.startswith("search "):
            topic = command[7:].strip()
            response = "Search URL: https://www.google.com/search?q=" + urllib.parse.quote_plus(topic)
        elif c == "open google":
            response = "https://www.google.com/"
        elif c == "open youtube":
            response = "https://www.youtube.com/"
        elif c in ("bye", "exit", "quit"):
            response = "Goodbye! Have a great day."
        else:
            response = "Sorry, I don't understand that command."
        st.success(response)
